Fixup for commit f6c6339d5e94
This patch fixes the following build error upon final link:

undefined reference to `nf_nat_redirect_ipv6'
relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `nf_nat_redirect_ipv6'